// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, dob)
VALUES ($1, $2)
RETURNING id, name, dob
`

type CreateUserParams struct {
	Name string
	Dob  time.Time
}

type CreateUserRow struct {
	ID   int32
	Name string
	Dob  time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Dob)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Name, &i.Dob)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, dob FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID   int32
	Name string
	Dob  time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Dob)
	return i, err
}

const listUsersPaginated = `-- name: ListUsersPaginated :many
SELECT id, name, dob 
FROM users 
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersPaginatedParams struct {
	Limit  int32
	Offset int32
}

type ListUsersPaginatedRow struct {
	ID   int32
	Name string
	Dob  time.Time
}

func (q *Queries) ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]ListUsersPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersPaginatedRow
	for rows.Next() {
		var i ListUsersPaginatedRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Dob); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, dob = $3
WHERE id = $1
RETURNING id, name, dob
`

type UpdateUserParams struct {
	ID   int32
	Name string
	Dob  time.Time
}

type UpdateUserRow struct {
	ID   int32
	Name string
	Dob  time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Name, arg.Dob)
	var i UpdateUserRow
	err := row.Scan(&i.ID, &i.Name, &i.Dob)
	return i, err
}
